import Head from 'next/head'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import Plan from '../components/Plan'
import Socials from '../components/Socials'
import Works from '../components/Works'

export default function Home() {
  return (
    <div className={""}>
      <Head>
        <title>UpBox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assests/Logo-1.png" />
      </Head>


      <main className='w-full '>
        <Navbar/>
        <Main/>
        <Plan/>
        <Works/>
        <Socials/>
      </main>
    </div>
  )
}
